### ISSUE TITLE
OpenVNMRJ on CentOS 7?

### ISSUE THREAD

**Issue by DavidGeeraerts** [tesch1/OpenVnmrJ#2]
Is it possible to get OpenVNMRJ (Mercury console distribution) to work with CentOS 7?
If I understand the documentation correctly for OpenVNMRJ, VNMRJ 4.2 needs to be already installed (?).
Where could I get VNMRJ 4.2 if I don't have it?
We have an old Varian\Agilent AS400 NMR, currently running on RHEL 5.x with VNMRJ 2.2D.
Our goal is to replace the computer, running CentOS 7 ideally, and if possible, OpenVNMRJ.

Thank you for  your time.
David Geeraerts
Scientific Computing Manager | Evergreen State College

**Comment by tesch1** [comment]
Hi David,
First I should point out that this issue is in my development fork of the main [OpenVnmrJ/OpenVnmrJ](https://github.com/OpenVnmrJ/OpenVnmrJ/) project, so I'm the only one who is likely to read this...  (once I send this I will turn off Issues for this repo (tesch1/OpenVnmrJ) since it's really just a workspace for me... I didnt' even realize it could accept issues.)
To the question - The main guy for OpenVnmrJ is @DanIverson.  I'm not an expert, more of a hobbyist (though indeed, I have done some work on getting OVJ to run on various OSs, including CentOS7), so I think you should start at SpinSights (https://spinsights.chem.agilent.com) and/or the main [OpenVnmrJ/OpenVnmrJ](https://github.com/OpenVnmrJ/OpenVnmrJ/) github.
Cheers,
Michael
